# Generated by Django 5.2.1 on 2025-06-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = []
