# Generated by Django 5.2.1 on 2025-08-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('guides', 'Educational & Learning Guides'), ('career', 'Career & Industry Articles'), ('success', 'Student Success Stories'), ('tips', 'Study Tips & Motivation')], default='guides', max_length=50),
        ),
    ]
