# Generated by Django 5.2.1 on 2025-09-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_playlist_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
